// Generated by CoffeeScript 2.7.0
/*
Introducing,

Even or Odd

A program written in Coffeescript
*/
var a, exit, prompt;

prompt = require("prompt-sync")();

a = prompt("Enter your number: ");

if (a % 2 === 0) {
  console.log(`${a}, even`);
} else {
  console.log(`${a}, odd`);
}

exit = function() {
  return console.log("Program Exit.");
};

setTimeout(exit, 3000);
